### ISSUE TITLE
document workaround for my_float floating-point variable issue

### ISSUE THREAD

**Issue by BenWibking** [BenWibking/gizmo-fork#4]
@ZipengHu Can you document what you did to fix the problem caused by `my_float` converting or saving the SLUG floating-point variables incorrectly as single-precision?

I just want to make sure the solution for this issue is written down somewhere.

**Comment by ZipengHu** [comment]
I have uploaded the new Config.sh file, where I comments: "When SLUG is used, input and output should be in double precision."

**Comment by BenWibking** [comment]
Did you create a pull request? I don't see it.

**Comment by BenWibking** [comment]
Fixed via https://github.com/BenWibking/gizmo-fork/pull/6
